# -*- coding: utf-8 -*-
"""SVDRecommenderSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15d37aY0uHoG_GW5w-iLcALb4OetOzf5g

Installs
"""

!pip install scikit-surprise
!pip install kagglehub

"""Downgrade numpy to a compatible version and reinstall surprise"""

!pip install numpy==1.23.5
!pip install scikit-surprise --no-binary scikit-surprise

"""Imports"""

# 📦 Imports
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from surprise import SVD, Dataset, Reader
from surprise.model_selection import cross_validate
import kagglehub
import warnings
import os
warnings.filterwarnings('ignore')

"""Importing dataset from kaggle"""

base_path = kagglehub.dataset_download("rounakbanik/the-movies-dataset")

movies = pd.read_csv(os.path.join(base_path, "movies_metadata.csv"), low_memory=False)
ratings = pd.read_csv(os.path.join(base_path, "ratings_small.csv"))
links = pd.read_csv(os.path.join(base_path, "links.csv"))
ratings.head()

"""Creating Reader object"""

min_rating = 0.5
max_rating = 5.0
reader = Reader(rating_scale=(min_rating, max_rating))

"""Cleaned data"""

data = Dataset.load_from_df(ratings[['userId', 'movieId', 'rating']], reader)

# Define algorithm
algo = SVD()
# Evaluate with cross-validation
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

trainset = data.build_full_trainset()
algo.fit(trainset)

ratings[ratings['userId'] == 1]

user_id = 1
movie_id = 5
predicted_rating = algo.predict(user_id, movie_id).est
print(f"Predicted rating for User {user_id} and Movie {movie_id}: {predicted_rating}")